version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sockwise_backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: sockwise_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
