global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'sockwise-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sockwise-backend:5000']

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
